{% set name = "gcnvplot" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=69
    - wheel
  run:
    - python >=3.10

test:
  imports:
    - gcnvplot
  commands:
    - gcnvplot --help

about:
  home: https://github.com/micknudsen/gcnvplot
  summary: Command-line tools for plotting GATK germline CNV results
  license: MIT
  license_file: LICENSE
